version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: claims_db
    ports:
      - "5204:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend123
    restart: always
    ports:
      - "3204:3204"
    depends_on:
      - postgres

  employee-claims:
    build: ./Employee-claims
    container_name: employee-claims11
    restart: always
    ports:
      - "8008:80"
    depends_on:
      - backend

  hr-claims:
    build: ./HR-claims
    container_name: hr-claims112
    restart: always
    ports:
      - "8009:80"
    depends_on:
      - backend

volumes:
  postgres-data:

