version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: claims_db
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  employee-claims:
    build: ./Employee-claims
    container_name: employee-claims
    restart: always
    ports:
      - "8003:80"
    depends_on:
      - backend

  hr-claims:
    build: ./HR-claims
    container_name: hr-claims
    restart: always
    ports:
      - "8004:80"
    depends_on:
      - backend

volumes:
  postgres-data:

